### ISSUE TITLE
Request for Complete EFI Folder

### ISSUE THREAD

**Issue by ubaimutl** [postkevone/razer-blade-stealth-13-oc#2]
Hi postkevone,

After following your guide, I'm have issues with audio, brightness control, trackpad functionality, and overheating. Could you please share your complete EFI folder ?

**Comment by postkevone** [comment]
[OC.zip](https://github.com/postkevone/razer-blade-stealth-13-oc/files/13797885/OC.zip)
I did not include the kext folder because of the file size limitation.
Also note that I have a modified BIOS with disabled dGPU, so you may need to add and enable SSDT-dGPU-Off, and revert the following changes:
https://github.com/postkevone/razer-blade-stealth-13-oc/tree/main/BIOS#notes
Other than that just follow the Dortania icelake laptop guide.
